<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\AfterSalesController;
use App\Http\Controllers\AdminReportController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\StorefrontController;
use App\Http\Controllers\SupportChatController;

Route::get('/', [StorefrontController::class, 'home'])->name('home');
Route::get('/shop', [StorefrontController::class, 'shop'])->name('shop');
Route::get('/watches', fn (\Illuminate\Http\Request $request, StorefrontController $store) => $store->shop($request, 'watch'))->name('watches');
Route::get('/jewelry', fn (\Illuminate\Http\Request $request, StorefrontController $store) => $store->shop($request, 'jewelry'))->name('jewelry');
Route::get('/products/{product:slug}', [StorefrontController::class, 'show'])->name('products.show');
Route::post('/products/{product:slug}/reviews', [ReviewController::class, 'store'])->middleware(['auth', 'throttle:6,1'])->name('products.reviews.store');
Route::post('/products/{product:slug}/cart', [CartController::class, 'store'])->name('cart.store');
Route::get('/cart', [CartController::class, 'index'])->name('cart.index');
Route::patch('/cart/items/{cartItem}', [CartController::class, 'update'])->name('cart.update');
Route::delete('/cart/items/{cartItem}', [CartController::class, 'destroy'])->name('cart.destroy');
Route::post('/cart/coupon', [CartController::class, 'applyCoupon'])->name('cart.coupon.apply');
Route::delete('/cart/coupon', [CartController::class, 'removeCoupon'])->name('cart.coupon.remove');
Route::get('/checkout/shipping', [CheckoutController::class, 'shipping'])->name('checkout.shipping');
Route::get('/checkout/locations/provinces', [CheckoutController::class, 'provinces'])->name('checkout.locations.provinces');
Route::get('/checkout/locations/wards', [CheckoutController::class, 'wards'])->name('checkout.locations.wards');
Route::get('/checkout/shipping/quote', [CheckoutController::class, 'quoteShipping'])->name('checkout.shipping.quote');
Route::post('/checkout/shipping', [CheckoutController::class, 'storeShipping'])->name('checkout.shipping.store');
Route::get('/checkout/payment', [CheckoutController::class, 'payment'])->name('checkout.payment');
Route::post('/checkout/place', [CheckoutController::class, 'place'])->name('checkout.place');
Route::get('/checkout/confirmation/{order}', [CheckoutController::class, 'confirmation'])->name('checkout.confirmation');
Route::get('/payments/vnpay/{order}/redirect', [PaymentController::class, 'vnpayRedirect'])->name('payments.vnpay.redirect');
Route::get('/payments/vnpay/return', [PaymentController::class, 'vnpayReturn'])->name('payments.vnpay.return');
Route::match(['get', 'post'], '/webhooks/vnpay', [PaymentController::class, 'vnpayIpn'])->name('payments.vnpay.ipn');
Route::get('/payments/paypal/{order}/redirect', [PaymentController::class, 'paypalRedirect'])->name('payments.paypal.redirect');
Route::get('/payments/paypal/return', [PaymentController::class, 'paypalReturn'])->name('payments.paypal.return');
Route::post('/webhooks/paypal', [PaymentController::class, 'paypalWebhook'])->name('payments.paypal.webhook');
Route::get('/track-order', [StorefrontController::class, 'trackingForm'])->name('tracking.form');
Route::post('/track-order', [StorefrontController::class, 'tracking'])->middleware('throttle:6,1')->name('tracking.search');
Route::get('/support/return', [AfterSalesController::class, 'returnForm'])->name('support.return.form');
Route::post('/support/return', [AfterSalesController::class, 'submitReturn'])->middleware('throttle:6,1')->name('support.return.submit');
Route::get('/support/warranty', [AfterSalesController::class, 'warrantyForm'])->name('support.warranty.form');
Route::post('/support/warranty', [AfterSalesController::class, 'submitWarranty'])->middleware('throttle:6,1')->name('support.warranty.submit');
Route::prefix('support/chat')->name('support.chat.')->group(function () {
    Route::get('/', [SupportChatController::class, 'current'])->middleware('throttle:120,1')->name('current');
    Route::post('/messages', [SupportChatController::class, 'message'])->middleware('throttle:20,1')->name('messages');
    Route::post('/handoff', [SupportChatController::class, 'handoff'])->middleware('throttle:10,1')->name('handoff');
    Route::post('/read', [SupportChatController::class, 'read'])->middleware('throttle:60,1')->name('read');
});
Route::middleware('guest')->group(function () { Route::get('/login', [AuthController::class, 'showLogin'])->name('login'); Route::post('/login', [AuthController::class, 'login'])->name('login.store'); Route::get('/register', [AuthController::class, 'showRegister'])->name('register'); Route::post('/register', [AuthController::class, 'register'])->name('register.store'); });
Route::post('/logout', [AuthController::class, 'logout'])->middleware('auth')->name('logout');
Route::get('/admin/reports/sales.csv', [AdminReportController::class, 'export'])->middleware('auth')->name('admin.reports.export');
Route::middleware('auth')->prefix('account')->name('account.')->group(function () {
    Route::get('/', [AccountController::class, 'dashboard'])->name('dashboard');
    Route::get('/profile', [AccountController::class, 'profile'])->name('profile');
    Route::patch('/profile', [AccountController::class, 'updateProfile'])->name('profile.update');
    Route::post('/addresses', [AccountController::class, 'storeAddress'])->name('addresses.store');
    Route::patch('/addresses/{address}/default', [AccountController::class, 'makeDefaultAddress'])->name('addresses.default');
    Route::delete('/addresses/{address}', [AccountController::class, 'destroyAddress'])->name('addresses.destroy');
    Route::get('/orders', [AccountController::class, 'orders'])->name('orders');
    Route::get('/orders/{order}', [AccountController::class, 'order'])->name('orders.show');
    Route::get('/notifications', [AccountController::class, 'notifications'])->name('notifications');
    Route::post('/notifications/read-all', [AccountController::class, 'readAllNotifications'])->name('notifications.read-all');
    Route::post('/notifications/{notification}/read', [AccountController::class, 'readNotification'])->name('notifications.read');
    Route::get('/benefits', [AccountController::class, 'benefits'])->name('benefits');
    Route::get('/wishlist', [AccountController::class, 'wishlist'])->name('wishlist');
    Route::post('/wishlist/{product}', [AccountController::class, 'toggleWishlist'])->name('wishlist.toggle');
    Route::get('/after-sales', [AccountController::class, 'afterSales'])->name('after-sales');
    Route::post('/after-sales/returns', [AccountController::class, 'submitReturn'])->middleware('throttle:6,1')->name('after-sales.returns.store');
    Route::post('/after-sales/warranties', [AccountController::class, 'submitWarranty'])->middleware('throttle:6,1')->name('after-sales.warranties.store');
});
